// import metadata type
import type { Metadata } from "next";
//import fonts from utils file
import { montserrat,roboto } from "./utils/fonts";
//import global css
import "./globals.css";

// create Metadata Tags
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`w-full h-screen bg-white overflow-hiddden ${montserrat} ${roboto}`}>
        {children}
      </body>
    </html>
  );
}
